function [fitresult, gof] = createFit_RhovsMs(Ms, rho)
% This code generates a curvefit for the case of Rho vs Ms, 
% using a list of Rho and Ms data
%  Create a fit.
%
%  Data for 'ρ vs. Ms' fit:
%      X Input: Ms
%      Y Output: rho
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Dec-2023 11:11:11


%% Fit: 'ρ vs. Ms'.
[xData, yData] = prepareCurveData( Ms, rho );

% Set up fittype and options.
ft                  = fittype( 'poly1' );
opts                = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust         = 'LAR';

% Fit model to data.
[fitresult, gof]    = fit( xData, yData, ft, opts );