function [fitresult, gof] = createFit_Chi0vsRho(rho, chi0)
%CREATEFIT(RHO,CHI0)
%  Create a fit.
%
%  Data for 'chi0 vs ρ' fit:
%      X Input: rho
%      Y Output: chi0
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Dec-2023 11:09:41


%% Fit: 'chi0 vs ρ'.
[xData, yData] = prepareCurveData( rho, chi0 );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [6.93404192065143e-05 0.00933209560612777 -8.40979135182607 -0.00199191475152703];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

