function [fitresult, gof] = createFit_RhoVsPhi(phi_data, rho_data)
%CREATEFIT(PHI_DATA,RHO_DATA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: phi_data
%      Y Output: rho_data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Dec-2023 12:03:49


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( phi_data, rho_data );

% Set up fittype and options.
ft = fittype( 'a*x+1000', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.392227019534168;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );


