function [fitresult, gof] = createFit_Chi0VsPhi(phi_data, Chi0_data)
%CREATEFIT(PHI_DATA,CHI0_DATA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: phi_data
%      Y Output: Chi0_data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Dec-2023 12:10:47


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( phi_data, Chi0_data );

% Set up fittype and options.
ft = fittype( 'a*x^b', 'independent', 'x', 'dependent', 'y' );
excludedPoints = xData > 5;
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.5147 1.469];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

